module Roglew
  module GL
    POINT_SPRITE_CULL_CENTER_ATIX = 0x60B4 unless const_defined? :POINT_SPRITE_CULL_CENTER_ATIX
    POINT_SPRITE_CULL_CLIP_ATIX   = 0x60B5 unless const_defined? :POINT_SPRITE_CULL_CLIP_ATIX
    POINT_SPRITE_CULL_MODE_ATIX   = 0x60B3 unless const_defined? :POINT_SPRITE_CULL_MODE_ATIX
    TEXTURE_POINT_MODE_ATIX       = 0x60B0 unless const_defined? :TEXTURE_POINT_MODE_ATIX
    TEXTURE_POINT_ONE_COORD_ATIX  = 0x60B1 unless const_defined? :TEXTURE_POINT_ONE_COORD_ATIX
    TEXTURE_POINT_SPRITE_ATIX     = 0x60B2 unless const_defined? :TEXTURE_POINT_SPRITE_ATIX
  end
end