module Roglew
  module GL
    POINT_SPRITE_CULL_CENTER_ATIX ||= 0x60B4
    POINT_SPRITE_CULL_CLIP_ATIX   ||= 0x60B5
    POINT_SPRITE_CULL_MODE_ATIX   ||= 0x60B3
    TEXTURE_POINT_MODE_ATIX       ||= 0x60B0
    TEXTURE_POINT_ONE_COORD_ATIX  ||= 0x60B1
    TEXTURE_POINT_SPRITE_ATIX     ||= 0x60B2
  end
end