module Roglew
  module GL
    FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D
    GEOMETRY_SHADER_INVOCATIONS        = 0x887F
    MAX_FRAGMENT_INTERPOLATION_OFFSET  = 0x8E5C
    MAX_GEOMETRY_SHADER_INVOCATIONS    = 0x8E5A
    MAX_VERTEX_STREAMS                 = 0x8E71
    MIN_FRAGMENT_INTERPOLATION_OFFSET  = 0x8E5B
  end
end