module Roglew
  module GL
    MAX_CUBE_MAP_TEXTURE_SIZE_ARB   = 0x851C unless const_defined? :MAX_CUBE_MAP_TEXTURE_SIZE_ARB
    NORMAL_MAP_ARB                  = 0x8511 unless const_defined? :NORMAL_MAP_ARB
    PROXY_TEXTURE_CUBE_MAP_ARB      = 0x851B unless const_defined? :PROXY_TEXTURE_CUBE_MAP_ARB
    REFLECTION_MAP_ARB              = 0x8512 unless const_defined? :REFLECTION_MAP_ARB
    TEXTURE_BINDING_CUBE_MAP_ARB    = 0x8514 unless const_defined? :TEXTURE_BINDING_CUBE_MAP_ARB
    TEXTURE_CUBE_MAP_ARB            = 0x8513 unless const_defined? :TEXTURE_CUBE_MAP_ARB
    TEXTURE_CUBE_MAP_NEGATIVE_X_ARB = 0x8516 unless const_defined? :TEXTURE_CUBE_MAP_NEGATIVE_X_ARB
    TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB = 0x8518 unless const_defined? :TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB
    TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB = 0x851A unless const_defined? :TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB
    TEXTURE_CUBE_MAP_POSITIVE_X_ARB = 0x8515 unless const_defined? :TEXTURE_CUBE_MAP_POSITIVE_X_ARB
    TEXTURE_CUBE_MAP_POSITIVE_Y_ARB = 0x8517 unless const_defined? :TEXTURE_CUBE_MAP_POSITIVE_Y_ARB
    TEXTURE_CUBE_MAP_POSITIVE_Z_ARB = 0x8519 unless const_defined? :TEXTURE_CUBE_MAP_POSITIVE_Z_ARB
  end
end