module Roglew
  module GL
    FRAGMENT_SHADER_ARB                 = 0x8B30 unless const_defined? :FRAGMENT_SHADER_ARB
    FRAGMENT_SHADER_DERIVATIVE_HINT_ARB = 0x8B8B unless const_defined? :FRAGMENT_SHADER_DERIVATIVE_HINT_ARB
    MAX_FRAGMENT_UNIFORM_COMPONENTS_ARB = 0x8B49 unless const_defined? :MAX_FRAGMENT_UNIFORM_COMPONENTS_ARB
  end
end