module Roglew
  module GL
    MAX_COMBINED_SHADER_OUTPUT_RESOURCES      = 0x8F39 unless const_defined? :MAX_COMBINED_SHADER_OUTPUT_RESOURCES
    MAX_COMBINED_SHADER_STORAGE_BLOCKS        = 0x90DC unless const_defined? :MAX_COMBINED_SHADER_STORAGE_BLOCKS
    MAX_COMPUTE_SHADER_STORAGE_BLOCKS         = 0x90DB unless const_defined? :MAX_COMPUTE_SHADER_STORAGE_BLOCKS
    MAX_FRAGMENT_SHADER_STORAGE_BLOCKS        = 0x90DA unless const_defined? :MAX_FRAGMENT_SHADER_STORAGE_BLOCKS
    MAX_GEOMETRY_SHADER_STORAGE_BLOCKS        = 0x90D7 unless const_defined? :MAX_GEOMETRY_SHADER_STORAGE_BLOCKS
    MAX_SHADER_STORAGE_BLOCK_SIZE             = 0x90DE unless const_defined? :MAX_SHADER_STORAGE_BLOCK_SIZE
    MAX_SHADER_STORAGE_BUFFER_BINDINGS        = 0x90DD unless const_defined? :MAX_SHADER_STORAGE_BUFFER_BINDINGS
    MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS    = 0x90D8 unless const_defined? :MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS
    MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9 unless const_defined? :MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS
    MAX_VERTEX_SHADER_STORAGE_BLOCKS          = 0x90D6 unless const_defined? :MAX_VERTEX_SHADER_STORAGE_BLOCKS
    SHADER_STORAGE_BARRIER_BIT                = 0x2000 unless const_defined? :SHADER_STORAGE_BARRIER_BIT
    SHADER_STORAGE_BUFFER                     = 0x90D2 unless const_defined? :SHADER_STORAGE_BUFFER
    SHADER_STORAGE_BUFFER_BINDING             = 0x90D3 unless const_defined? :SHADER_STORAGE_BUFFER_BINDING
    SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT    = 0x90DF unless const_defined? :SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT
    SHADER_STORAGE_BUFFER_SIZE                = 0x90D5 unless const_defined? :SHADER_STORAGE_BUFFER_SIZE
    SHADER_STORAGE_BUFFER_START               = 0x90D4 unless const_defined? :SHADER_STORAGE_BUFFER_START
  end
end

module GL_ARB_shader_storage_buffer_object
  module RenderContext
    include Roglew::GLExtension

    functions [:glShaderStorageBlockBinding, [ :uint, :uint, :uint ], :void]
  end
end

