module Roglew
  module GL
    COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB   = 0x8E8E unless const_defined? :COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB
    COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_ARB = 0x8E8F unless const_defined? :COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_ARB
    COMPRESSED_RGBA_BPTC_UNORM_ARB         = 0x8E8C unless const_defined? :COMPRESSED_RGBA_BPTC_UNORM_ARB
    COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB   = 0x8E8D unless const_defined? :COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB
  end
end