module Roglew
  module GL
    MAX_RECTANGLE_TEXTURE_SIZE_ARB = 0x84F8 unless const_defined? :MAX_RECTANGLE_TEXTURE_SIZE_ARB
    PROXY_TEXTURE_RECTANGLE_ARB    = 0x84F7 unless const_defined? :PROXY_TEXTURE_RECTANGLE_ARB
    SAMPLER_2D_RECT_ARB            = 0x8B63 unless const_defined? :SAMPLER_2D_RECT_ARB
    SAMPLER_2D_RECT_SHADOW_ARB     = 0x8B64 unless const_defined? :SAMPLER_2D_RECT_SHADOW_ARB
    TEXTURE_BINDING_RECTANGLE_ARB  = 0x84F6 unless const_defined? :TEXTURE_BINDING_RECTANGLE_ARB
    TEXTURE_RECTANGLE_ARB          = 0x84F5 unless const_defined? :TEXTURE_RECTANGLE_ARB
  end
end