module Roglew
  module GL
    MAX_RECTANGLE_TEXTURE_SIZE_ARB = 0x84F8
    PROXY_TEXTURE_RECTANGLE_ARB    = 0x84F7
    SAMPLER_2D_RECT_ARB            = 0x8B63 unless const_defined?(:SAMPLER_2D_RECT_ARB)
    SAMPLER_2D_RECT_SHADOW_ARB     = 0x8B64 unless const_defined?(:SAMPLER_2D_RECT_SHADOW_ARB)
    TEXTURE_BINDING_RECTANGLE_ARB  = 0x84F6
    TEXTURE_RECTANGLE_ARB          = 0x84F5
  end
end