module Roglew
  module GL
    FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D unless const_defined?(:FRAGMENT_INTERPOLATION_OFFSET_BITS)
    GEOMETRY_SHADER_INVOCATIONS        = 0x887F unless const_defined?(:GEOMETRY_SHADER_INVOCATIONS)
    MAX_FRAGMENT_INTERPOLATION_OFFSET  = 0x8E5C unless const_defined?(:MAX_FRAGMENT_INTERPOLATION_OFFSET)
    MAX_GEOMETRY_SHADER_INVOCATIONS    = 0x8E5A unless const_defined?(:MAX_GEOMETRY_SHADER_INVOCATIONS)
    MAX_VERTEX_STREAMS                 = 0x8E71
    MIN_FRAGMENT_INTERPOLATION_OFFSET  = 0x8E5B unless const_defined?(:MIN_FRAGMENT_INTERPOLATION_OFFSET)
  end
end