module Roglew
  module GL
    MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB = 0x8F9F unless const_defined? :MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB
    MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB     = 0x8E5F unless const_defined? :MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB
    MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB     = 0x8E5E unless const_defined? :MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB
  end
end