module Roglew
  module GL
    PACK_COMPRESSED_BLOCK_DEPTH    = 0x912D unless const_defined? :PACK_COMPRESSED_BLOCK_DEPTH
    PACK_COMPRESSED_BLOCK_HEIGHT   = 0x912C unless const_defined? :PACK_COMPRESSED_BLOCK_HEIGHT
    PACK_COMPRESSED_BLOCK_SIZE     = 0x912E unless const_defined? :PACK_COMPRESSED_BLOCK_SIZE
    PACK_COMPRESSED_BLOCK_WIDTH    = 0x912B unless const_defined? :PACK_COMPRESSED_BLOCK_WIDTH
    UNPACK_COMPRESSED_BLOCK_DEPTH  = 0x9129 unless const_defined? :UNPACK_COMPRESSED_BLOCK_DEPTH
    UNPACK_COMPRESSED_BLOCK_HEIGHT = 0x912 unless const_defined? :UNPACK_COMPRESSED_BLOCK_HEIGHT
    UNPACK_COMPRESSED_BLOCK_SIZE   = 0x912A unless const_defined? :UNPACK_COMPRESSED_BLOCK_SIZE
    UNPACK_COMPRESSED_BLOCK_WIDTH  = 0x9127 unless const_defined? :UNPACK_COMPRESSED_BLOCK_WIDTH
  end
end