module Roglew
  module GL
    TEXTURE_CUBE_MAP_ARRAY_ARB              = 0x9009 unless const_defined? :TEXTURE_CUBE_MAP_ARRAY_ARB
    TEXTURE_BINDING_CUBE_MAP_ARRAY_ARB      = 0x900A unless const_defined? :TEXTURE_BINDING_CUBE_MAP_ARRAY_ARB
    PROXY_TEXTURE_CUBE_MAP_ARRAY_ARB        = 0x900B unless const_defined? :PROXY_TEXTURE_CUBE_MAP_ARRAY_ARB
    SAMPLER_CUBE_MAP_ARRAY_ARB              = 0x900C unless const_defined? :SAMPLER_CUBE_MAP_ARRAY_ARB
    SAMPLER_CUBE_MAP_ARRAY_SHADOW_ARB       = 0x900D unless const_defined? :SAMPLER_CUBE_MAP_ARRAY_SHADOW_ARB
    INT_SAMPLER_CUBE_MAP_ARRAY_ARB          = 0x900E unless const_defined? :INT_SAMPLER_CUBE_MAP_ARRAY_ARB
    UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_ARB = 0x900F unless const_defined? :UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_ARB
  end
end