module Roglew
  module GL
    PACK_COMPRESSED_BLOCK_DEPTH    ||= 0x912D
    PACK_COMPRESSED_BLOCK_HEIGHT   ||= 0x912C
    PACK_COMPRESSED_BLOCK_SIZE     ||= 0x912E
    PACK_COMPRESSED_BLOCK_WIDTH    ||= 0x912B
    UNPACK_COMPRESSED_BLOCK_DEPTH  ||= 0x9129
    UNPACK_COMPRESSED_BLOCK_HEIGHT ||= 0x912
    UNPACK_COMPRESSED_BLOCK_SIZE   ||= 0x912A
    UNPACK_COMPRESSED_BLOCK_WIDTH  ||= 0x9127
  end
end