module Roglew
  module GL
    PIXEL_PACK_BUFFER_ARB           = 0x88EB
    PIXEL_PACK_BUFFER_BINDING_ARB   = 0x88ED
    PIXEL_UNPACK_BUFFER_ARB         = 0x88EC
    PIXEL_UNPACK_BUFFER_BINDING_ARB = 0x88EF
    SAMPLES_PASSED_ARB              = 0x8914
  end
end