module Roglew
  module GL
    MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB ||= 0x8F9F
    MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB     ||= 0x8E5F
    MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB     ||= 0x8E5E
  end
end