module Roglew
  module GL
    GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX = 0x9049
    GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX         = 0x9047
    GPU_MEMORY_INFO_EVICTED_MEMORY_NVX           = 0x904B
    GPU_MEMORY_INFO_EVICTION_COUNT_NVX           = 0x904A
    GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX   = 0x9048
  end
end