module Roglew
  module GL
    FRAGMENT_PROGRAM_INTERPOLATION_OFFSET_BITS_NV = 0x8E5D
    MAX_FRAGMENT_INTERPOLATION_OFFSET_NV          = 0x8E5C
    MAX_GEOMETRY_PROGRAM_INVOCATIONS_NV           = 0x8E5A
    MAX_PROGRAM_TEXTURE_GATHER_OFFSET_NV          = 0x8E5F
    MIN_FRAGMENT_INTERPOLATION_OFFSET_NV          = 0x8E5B
    MIN_PROGRAM_TEXTURE_GATHER_OFFSET_NV          = 0x8E5E
  end
end