module Roglew
  module GL
    ASYNC_DRAW_PIXELS_SGIX     ||= 0x835D
    ASYNC_READ_PIXELS_SGIX     ||= 0x835E
    ASYNC_TEX_IMAGE_SGIX       ||= 0x835C
    MAX_ASYNC_DRAW_PIXELS_SGIX ||= 0x8360
    MAX_ASYNC_READ_PIXELS_SGIX ||= 0x8361
    MAX_ASYNC_TEX_IMAGE_SGIX   ||= 0x835F
  end
end