module Roglew
  module GLX
    CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB = 0x8256
    CONTEXT_ROBUST_ACCESS_BIT_ARB           = 0x00000004
    LOSE_CONTEXT_ON_RESET_ARB               = 0x8252
    NO_RESET_NOTIFICATION_ARB               = 0x8261
  end
end