module GL_core_1_4
  module RenderContext
    include GLExtension

    functions [:glBlendColor, [ :float, :float, :float, :float ], :void],
              [:glBlendEquation, [ :uint ], :void],
              [:glBlendFuncSeparate, [ :uint, :uint, :uint, :uint ], :void],
              [:glFogCoordd, [ :double ], :void],
              [:glFogCoorddv, [ :pointer ], :void],
              [:glFogCoordf, [ :float ], :void],
              [:glFogCoordfv, [ :pointer ], :void],
              [:glFogCoordPointer, [ :uint, :int, :pointer ], :void],
              [:glMultiDrawArrays, [ :uint, :pointer, :pointer, :int ], :void],
              [:glMultiDrawElements, [ :uint, :pointer, :uint, :pointer, :int ], :void],
              [:glPointParameterf, [ :uint, :float ], :void],
              [:glPointParameterfv, [ :uint, :pointer ], :void],
              [:glPointParameteri, [ :uint, :int ], :void],
              [:glPointParameteriv, [ :uint, :pointer ], :void],
              [:glSecondaryColor3b, [ :char, :char, :char ], :void],
              [:glSecondaryColor3bv, [ :pointer ], :void],
              [:glSecondaryColor3d, [ :double, :double, :double ], :void],
              [:glSecondaryColor3dv, [ :pointer ], :void],
              [:glSecondaryColor3f, [ :float, :float, :float ], :void],
              [:glSecondaryColor3fv, [ :pointer ], :void],
              [:glSecondaryColor3i, [ :int, :int, :int ], :void],
              [:glSecondaryColor3iv, [ :pointer ], :void],
              [:glSecondaryColor3s, [ :short, :short, :short ], :void],
              [:glSecondaryColor3sv, [ :pointer ], :void],
              [:glSecondaryColor3ub, [ :uchar, :uchar, :uchar ], :void],
              [:glSecondaryColor3ubv, [ :pointer ], :void],
              [:glSecondaryColor3ui, [ :uint, :uint, :uint ], :void],
              [:glSecondaryColor3uiv, [ :pointer ], :void],
              [:glSecondaryColor3us, [ :ushort, :ushort, :ushort ], :void],
              [:glSecondaryColor3usv, [ :pointer ], :void],
              [:glSecondaryColorPointer, [ :int, :uint, :int, :pointer ], :void],
              [:glWindowPos2d, [ :double, :double ], :void],
              [:glWindowPos2dv, [ :pointer ], :void],
              [:glWindowPos2f, [ :float, :float ], :void],
              [:glWindowPos2fv, [ :pointer ], :void],
              [:glWindowPos2i, [ :int, :int ], :void],
              [:glWindowPos2iv, [ :pointer ], :void],
              [:glWindowPos2s, [ :short, :short ], :void],
              [:glWindowPos2sv, [ :pointer ], :void],
              [:glWindowPos3d, [ :double, :double, :double ], :void],
              [:glWindowPos3dv, [ :pointer ], :void],
              [:glWindowPos3f, [ :float, :float, :float ], :void],
              [:glWindowPos3fv, [ :pointer ], :void],
              [:glWindowPos3i, [ :int, :int, :int ], :void],
              [:glWindowPos3iv, [ :pointer ], :void],
              [:glWindowPos3s, [ :short, :short, :short ], :void],
              [:glWindowPos3sv, [ :pointer ], :void]

  end
end