module GL_core_3_0
  module RenderContext
    include GLExtension

    functions [:glBeginConditionalRender, [ :uint, :uint ], :void],
              [:glBeginTransformFeedback, [ :uint ], :void],
              [:glBindFragDataLocation, [ :uint, :uint, :string ], :void],
              [:glClampColor, [ :uint, :uint ], :void],
              [:glClearBufferfi, [ :uint, :int, :float, :int ], :void],
              [:glClearBufferfv, [ :uint, :int, :pointer ], :void],
              [:glClearBufferiv, [ :uint, :int, :pointer ], :void],
              [:glClearBufferuiv, [ :uint, :int, :pointer ], :void],
              [:glColorMaski, [ :uint, :uchar, :uchar, :uchar, :uchar ], :void],
              [:glDisablei, [ :uint, :uint ], :void],
              [:glEnablei, [ :uint, :uint ], :void],
              [:glEndConditionalRender, [  ], :void],
              [:glEndTransformFeedback, [  ], :void],
              [:glGetBooleani_v, [ :uint, :uint, :pointer ], :void],
              [:glGetFragDataLocation, [ :uint, :string ], :int],
              [:glGetStringi, [ :uint, :uint ], :string],
              [:glGetTexParameterIiv, [ :uint, :uint, :pointer ], :void],
              [:glGetTexParameterIuiv, [ :uint, :uint, :pointer ], :void],
              [:glGetTransformFeedbackVarying, [ :uint, :uint, :int, :pointer, :pointer, :pointer, :string ], :void],
              [:glGetUniformuiv, [ :uint, :int, :pointer ], :void],
              [:glGetVertexAttribIiv, [ :uint, :uint, :pointer ], :void],
              [:glGetVertexAttribIuiv, [ :uint, :uint, :pointer ], :void],
              [:glIsEnabledi, [ :uint, :uint ], :uchar],
              [:glTexParameterIiv, [ :uint, :uint, :pointer ], :void],
              [:glTexParameterIuiv, [ :uint, :uint, :pointer ], :void],
              [:glTransformFeedbackVaryings, [ :uint, :int, :pointer, :uint ], :void],
              [:glUniform1ui, [ :int, :uint ], :void],
              [:glUniform1uiv, [ :int, :int, :pointer ], :void],
              [:glUniform2ui, [ :int, :uint, :uint ], :void],
              [:glUniform2uiv, [ :int, :int, :pointer ], :void],
              [:glUniform3ui, [ :int, :uint, :uint, :uint ], :void],
              [:glUniform3uiv, [ :int, :int, :pointer ], :void],
              [:glUniform4ui, [ :int, :uint, :uint, :uint, :uint ], :void],
              [:glUniform4uiv, [ :int, :int, :pointer ], :void],
              [:glVertexAttribI1i, [ :uint, :int ], :void],
              [:glVertexAttribI1iv, [ :uint, :pointer ], :void],
              [:glVertexAttribI1ui, [ :uint, :uint ], :void],
              [:glVertexAttribI1uiv, [ :uint, :pointer ], :void],
              [:glVertexAttribI2i, [ :uint, :int, :int ], :void],
              [:glVertexAttribI2iv, [ :uint, :pointer ], :void],
              [:glVertexAttribI2ui, [ :uint, :uint, :uint ], :void],
              [:glVertexAttribI2uiv, [ :uint, :pointer ], :void],
              [:glVertexAttribI3i, [ :uint, :int, :int, :int ], :void],
              [:glVertexAttribI3iv, [ :uint, :pointer ], :void],
              [:glVertexAttribI3ui, [ :uint, :uint, :uint, :uint ], :void],
              [:glVertexAttribI3uiv, [ :uint, :pointer ], :void],
              [:glVertexAttribI4bv, [ :uint, :pointer ], :void],
              [:glVertexAttribI4i, [ :uint, :int, :int, :int, :int ], :void],
              [:glVertexAttribI4iv, [ :uint, :pointer ], :void],
              [:glVertexAttribI4sv, [ :uint, :pointer ], :void],
              [:glVertexAttribI4ubv, [ :uint, :pointer ], :void],
              [:glVertexAttribI4ui, [ :uint, :uint, :uint, :uint, :uint ], :void],
              [:glVertexAttribI4uiv, [ :uint, :pointer ], :void],
              [:glVertexAttribI4usv, [ :uint, :pointer ], :void],
              [:glVertexAttribIPointer, [ :uint, :int, :uint, :int, :pointer ], :void]
  end
end