Roglew::GL.instance_eval do
  @functions = [
    [ :Accum, [ :uint, :float ], :void ],
    [ :AlphaFunc, [ :uint, :float ], :void ],
    [ :AreTexturesResident, [ :int, :pointer, :pointer ], :bool ],
    [ :ArrayElement, [ :int ], :void ],
    [ :Begin, [ :uint ], :void ],
    [ :BindTexture, [ :uint, :uint ], :void ],
    [ :Bitmap, [ :int, :int, :float, :float, :float, :float, :pointer ], :void ],
    [ :BlendFunc, [ :uint, :uint ], :void ],
    [ :CallList, [ :uint ], :void ],
    [ :CallLists, [ :int, :uint, :pointer ], :void ],
    [ :Clear, [ :uint ], :void ],
    [ :ClearAccum, [ :float, :float, :float, :float ], :void ],
    [ :ClearColor, [ :float, :float, :float, :float ], :void ],
    [ :ClearDepth, [ :double ], :void ],
    [ :ClearIndex, [ :float ], :void ],
    [ :ClearStencil, [ :int ], :void ],
    [ :ClipPlane, [ :uint, :pointer ], :void ],
    [ :Color3b, [ :char, :char, :char ], :void ],
    [ :Color3bv, [ :pointer ], :void ],
    [ :Color3d, [ :double, :double, :double ], :void ],
    [ :Color3dv, [ :pointer ], :void ],
    [ :Color3f, [ :float, :float, :float ], :void ],
    [ :Color3fv, [ :pointer ], :void ],
    [ :Color3i, [ :int, :int, :int ], :void ],
    [ :Color3iv, [ :pointer ], :void ],
    [ :Color3s, [ :short, :short, :short ], :void ],
    [ :Color3sv, [ :pointer ], :void ],
    [ :Color3ub, [ :uchar, :uchar, :uchar ], :void ],
    [ :Color3ubv, [ :pointer ], :void ],
    [ :Color3ui, [ :uint, :uint, :uint ], :void ],
    [ :Color3uiv, [ :pointer ], :void ],
    [ :Color3us, [ :ushort, :ushort, :ushort ], :void ],
    [ :Color3usv, [ :pointer ], :void ],
    [ :Color4b, [ :char, :char, :char, :char ], :void ],
    [ :Color4bv, [ :pointer ], :void ],
    [ :Color4d, [ :double, :double, :double, :double ], :void ],
    [ :Color4dv, [ :pointer ], :void ],
    [ :Color4f, [ :float, :float, :float, :float ], :void ],
    [ :Color4fv, [ :pointer ], :void ],
    [ :Color4i, [ :int, :int, :int, :int ], :void ],
    [ :Color4iv, [ :pointer ], :void ],
    [ :Color4s, [ :short, :short, :short, :short ], :void ],
    [ :Color4sv, [ :pointer ], :void ],
    [ :Color4ub, [ :uchar, :uchar, :uchar, :uchar ], :void ],
    [ :Color4ubv, [ :pointer ], :void ],
    [ :Color4ui, [ :uint, :uint, :uint, :uint ], :void ],
    [ :Color4uiv, [ :pointer ], :void ],
    [ :Color4us, [ :ushort, :ushort, :ushort, :ushort ], :void ],
    [ :Color4usv, [ :pointer ], :void ],
    [ :ColorMask, [ :uchar, :uchar, :uchar, :uchar ], :void ],
    [ :ColorMaterial, [ :uint, :uint ], :void ],
    [ :ColorPointer, [ :int, :uint, :int, :pointer ], :void ],
    [ :CopyPixels, [ :int, :int, :int, :int, :uint ], :void ],
    [ :CopyTexImage1D, [ :uint, :int, :uint, :int, :int, :int, :int ], :void ],
    [ :CopyTexImage2D, [ :uint, :int, :uint, :int, :int, :int, :int, :int ], :void ],
    [ :CopyTexSubImage1D, [ :uint, :int, :int, :int, :int, :int ], :void ],
    [ :CopyTexSubImage2D, [ :uint, :int, :int, :int, :int, :int, :int, :int ], :void ],
    [ :CullFace, [ :uint ], :void ],
    [ :DeleteLists, [ :uint, :int ], :void ],
    [ :DeleteTextures, [ :int, :pointer ], :void ],
    [ :DepthFunc, [ :uint ], :void ],
    [ :DepthMask, [ :uchar ], :void ],
    [ :DepthRange, [ :double, :double ], :void ],
    [ :Disable, [ :uint ], :void ],
    [ :DisableClientState, [ :uint ], :void ],
    [ :DrawArrays, [ :uint, :int, :int ], :void ],
    [ :DrawBuffer, [ :uint ], :void ],
    [ :DrawElements, [ :uint, :int, :uint, :pointer ], :void ],
    [ :DrawPixels, [ :int, :int, :uint, :uint, :pointer ], :void ],
    [ :EdgeFlag, [ :uchar ], :void ],
    [ :EdgeFlagPointer, [ :int, :pointer ], :void ],
    [ :EdgeFlagv, [ :pointer ], :void ],
    [ :Enable, [ :uint ], :void ],
    [ :EnableClientState, [ :uint ], :void ],
    [ :End, [  ], :void ],
    [ :EndList, [  ], :void ],
    [ :EvalCoord1d, [ :double ], :void ],
    [ :EvalCoord1dv, [ :pointer ], :void ],
    [ :EvalCoord1f, [ :float ], :void ],
    [ :EvalCoord1fv, [ :pointer ], :void ],
    [ :EvalCoord2d, [ :double, :double ], :void ],
    [ :EvalCoord2dv, [ :pointer ], :void ],
    [ :EvalCoord2f, [ :float, :float ], :void ],
    [ :EvalCoord2fv, [ :pointer ], :void ],
    [ :EvalMesh1, [ :uint, :int, :int ], :void ],
    [ :EvalMesh2, [ :uint, :int, :int, :int, :int ], :void ],
    [ :EvalPoint1, [ :int ], :void ],
    [ :EvalPoint2, [ :int, :int ], :void ],
    [ :FeedbackBuffer, [ :int, :uint, :pointer ], :void ],
    [ :Finish, [  ], :void ],
    [ :Flush, [  ], :void ],
    [ :Fogf, [ :uint, :float ], :void ],
    [ :Fogfv, [ :uint, :pointer ], :void ],
    [ :Fogi, [ :uint, :int ], :void ],
    [ :Fogiv, [ :uint, :pointer ], :void ],
    [ :FrontFace, [ :uint ], :void ],
    [ :Frustum, [ :double, :double, :double, :double, :double, :double ], :void ],
    [ :GenLists, [ :int ], :uint ],
    [ :GenTextures, [ :int, :pointer ], :void ],
    [ :GetBooleanv, [ :uint, :pointer ], :void ],
    [ :GetClipPlane, [ :uint, :pointer ], :void ],
    [ :GetDoublev, [ :uint, :pointer ], :void ],
    [ :GetError, [  ], :uint ],
    [ :GetFloatv, [ :uint, :pointer ], :void ],
    [ :GetIntegerv, [ :uint, :pointer ], :void ],
    [ :GetLightfv, [ :uint, :uint, :pointer ], :void ],
    [ :GetLightiv, [ :uint, :uint, :pointer ], :void ],
    [ :GetMapdv, [ :uint, :uint, :pointer ], :void ],
    [ :GetMapfv, [ :uint, :uint, :pointer ], :void ],
    [ :GetMapiv, [ :uint, :uint, :pointer ], :void ],
    [ :GetMaterialfv, [ :uint, :uint, :pointer ], :void ],
    [ :GetMaterialiv, [ :uint, :uint, :pointer ], :void ],
    [ :GetPixelMapfv, [ :uint, :pointer ], :void ],
    [ :GetPixelMapuiv, [ :uint, :pointer ], :void ],
    [ :GetPixelMapusv, [ :uint, :pointer ], :void ],
    [ :GetPointerv, [ :uint, :pointer ], :void ],
    [ :GetPolygonStipple, [ :pointer ], :void ],
    [ :GetString, [ :uint ], :string ],
    [ :GetTexEnvfv, [ :uint, :uint, :pointer ], :void ],
    [ :GetTexEnviv, [ :uint, :uint, :pointer ], :void ],
    [ :GetTexGendv, [ :uint, :uint, :pointer ], :void ],
    [ :GetTexGenfv, [ :uint, :uint, :pointer ], :void ],
    [ :GetTexGeniv, [ :uint, :uint, :pointer ], :void ],
    [ :GetTexImage, [ :uint, :int, :uint, :uint, :pointer ], :void ],
    [ :GetTexLevelParameterfv, [ :uint, :int, :uint, :pointer ], :void ],
    [ :GetTexLevelParameteriv, [ :uint, :int, :uint, :pointer ], :void ],
    [ :GetTexParameterfv, [ :uint, :uint, :pointer ], :void ],
    [ :GetTexParameteriv, [ :uint, :uint, :pointer ], :void ],
    [ :Hint, [ :uint, :uint ], :void ],
    [ :Indexd, [ :double ], :void ],
    [ :Indexdv, [ :pointer ], :void ],
    [ :Indexf, [ :float ], :void ],
    [ :Indexfv, [ :pointer ], :void ],
    [ :Indexi, [ :int ], :void ],
    [ :Indexiv, [ :pointer ], :void ],
    [ :IndexMask, [ :uint ], :void ],
    [ :IndexPointer, [ :uint, :int, :pointer ], :void ],
    [ :Indexs, [ :short ], :void ],
    [ :Indexsv, [ :pointer ], :void ],
    [ :Indexub, [ :uchar ], :void ],
    [ :Indexubv, [ :pointer ], :void ],
    [ :InitNames, [  ], :void ],
    [ :InterleavedArrays, [ :uint, :int, :pointer ], :void ],
    [ :IsEnabled, [ :uint ], :uchar ],
    [ :IsList, [ :uint ], :uchar ],
    [ :IsTexture, [ :uint ], :uchar ],
    [ :Lightf, [ :uint, :uint, :float ], :void ],
    [ :Lightfv, [ :uint, :uint, :pointer ], :void ],
    [ :Lighti, [ :uint, :uint, :int ], :void ],
    [ :Lightiv, [ :uint, :uint, :pointer ], :void ],
    [ :LightModelf, [ :uint, :float ], :void ],
    [ :LightModelfv, [ :uint, :pointer ], :void ],
    [ :LightModeli, [ :uint, :int ], :void ],
    [ :LightModeliv, [ :uint, :pointer ], :void ],
    [ :LineStipple, [ :int, :ushort ], :void ],
    [ :LineWidth, [ :float ], :void ],
    [ :ListBase, [ :uint ], :void ],
    [ :LoadIdentity, [  ], :void ],
    [ :LoadMatrixd, [ :pointer ], :void ],
    [ :LoadMatrixf, [ :pointer ], :void ],
    [ :LoadName, [ :uint ], :void ],
    [ :LogicOp, [ :uint ], :void ],
    [ :Map1d, [ :uint, :double, :double, :int, :int, :pointer ], :void ],
    [ :Map1f, [ :uint, :float, :float, :int, :int, :pointer ], :void ],
    [ :Map2d, [ :uint, :double, :double, :int, :int, :double, :double, :int, :int, :pointer ], :void ],
    [ :Map2f, [ :uint, :float, :float, :int, :int, :float, :float, :int, :int, :pointer ], :void ],
    [ :MapGrid1d, [ :int, :double, :double ], :void ],
    [ :MapGrid1f, [ :int, :float, :float ], :void ],
    [ :MapGrid2d, [ :int, :double, :double, :int, :double, :double ], :void ],
    [ :MapGrid2f, [ :int, :float, :float, :int, :float, :float ], :void ],
    [ :Materialf, [ :uint, :uint, :float ], :void ],
    [ :Materialfv, [ :uint, :uint, :pointer ], :void ],
    [ :Materiali, [ :uint, :uint, :int ], :void ],
    [ :Materialiv, [ :uint, :uint, :pointer ], :void ],
    [ :MatrixMode, [ :uint ], :void ],
    [ :MultMatrixd, [ :pointer ], :void ],
    [ :MultMatrixf, [ :pointer ], :void ],
    [ :NewList, [ :uint, :uint ], :void ],
    [ :Normal3b, [ :char, :char, :char ], :void ],
    [ :Normal3bv, [ :pointer ], :void ],
    [ :Normal3d, [ :double, :double, :double ], :void ],
    [ :Normal3dv, [ :pointer ], :void ],
    [ :Normal3f, [ :float, :float, :float ], :void ],
    [ :Normal3fv, [ :pointer ], :void ],
    [ :Normal3i, [ :int, :int, :int ], :void ],
    [ :Normal3iv, [ :pointer ], :void ],
    [ :Normal3s, [ :short, :short, :short ], :void ],
    [ :Normal3sv, [ :pointer ], :void ],
    [ :NormalPointer, [ :uint, :int, :pointer ], :void ],
    [ :Ortho, [ :double, :double, :double, :double, :double, :double ], :void ],
    [ :PassThrough, [ :float ], :void ],
    [ :PixelMapfv, [ :uint, :int, :pointer ], :void ],
    [ :PixelMapuiv, [ :uint, :int, :pointer ], :void ],
    [ :PixelMapusv, [ :uint, :int, :pointer ], :void ],
    [ :PixelStoref, [ :uint, :float ], :void ],
    [ :PixelStorei, [ :uint, :int ], :void ],
    [ :PixelTransferf, [ :uint, :float ], :void ],
    [ :PixelTransferi, [ :uint, :int ], :void ],
    [ :PixelZoom, [ :float, :float ], :void ],
    [ :PointSize, [ :float ], :void ],
    [ :PolygonMode, [ :uint, :uint ], :void ],
    [ :PolygonOffset, [ :float, :float ], :void ],
    [ :PolygonStipple, [ :pointer ], :void ],
    [ :PopAttrib, [  ], :void ],
    [ :PopClientAttrib, [  ], :void ],
    [ :PopMatrix, [  ], :void ],
    [ :PopName, [  ], :void ],
    [ :PrioritizeTextures, [ :int, :pointer, :pointer ], :void ],
    [ :PushAttrib, [ :uint ], :void ],
    [ :PushClientAttrib, [ :uint ], :void ],
    [ :PushMatrix, [  ], :void ],
    [ :PushName, [ :uint ], :void ],
    [ :RasterPos2d, [ :double, :double ], :void ],
    [ :RasterPos2dv, [ :pointer ], :void ],
    [ :RasterPos2f, [ :float, :float ], :void ],
    [ :RasterPos2fv, [ :pointer ], :void ],
    [ :RasterPos2i, [ :int, :int ], :void ],
    [ :RasterPos2iv, [ :pointer ], :void ],
    [ :RasterPos2s, [ :short, :short ], :void ],
    [ :RasterPos2sv, [ :pointer ], :void ],
    [ :RasterPos3d, [ :double, :double, :double ], :void ],
    [ :RasterPos3dv, [ :pointer ], :void ],
    [ :RasterPos3f, [ :float, :float, :float ], :void ],
    [ :RasterPos3fv, [ :pointer ], :void ],
    [ :RasterPos3i, [ :int, :int, :int ], :void ],
    [ :RasterPos3iv, [ :pointer ], :void ],
    [ :RasterPos3s, [ :short, :short, :short ], :void ],
    [ :RasterPos3sv, [ :pointer ], :void ],
    [ :RasterPos4d, [ :double, :double, :double, :double ], :void ],
    [ :RasterPos4dv, [ :pointer ], :void ],
    [ :RasterPos4f, [ :float, :float, :float, :float ], :void ],
    [ :RasterPos4fv, [ :pointer ], :void ],
    [ :RasterPos4i, [ :int, :int, :int, :int ], :void ],
    [ :RasterPos4iv, [ :pointer ], :void ],
    [ :RasterPos4s, [ :short, :short, :short, :short ], :void ],
    [ :RasterPos4sv, [ :pointer ], :void ],
    [ :ReadBuffer, [ :uint ], :void ],
    [ :ReadPixels, [ :int, :int, :int, :int, :uint, :uint, :pointer ], :void ],
    [ :Rectd, [ :double, :double, :double, :double ], :void ],
    [ :Rectdv, [ :pointer, :pointer ], :void ],
    [ :Rectf, [ :float, :float, :float, :float ], :void ],
    [ :Rectfv, [ :pointer, :pointer ], :void ],
    [ :Recti, [ :int, :int, :int, :int ], :void ],
    [ :Rectiv, [ :pointer, :pointer ], :void ],
    [ :Rects, [ :short, :short, :short, :short ], :void ],
    [ :Rectsv, [ :pointer, :pointer ], :void ],
    [ :RenderMode, [ :uint ], :int ],
    [ :Rotated, [ :double, :double, :double, :double ], :void ],
    [ :Rotatef, [ :float, :float, :float, :float ], :void ],
    [ :Scaled, [ :double, :double, :double ], :void ],
    [ :Scalef, [ :float, :float, :float ], :void ],
    [ :Scissor, [ :int, :int, :int, :int ], :void ],
    [ :SelectBuffer, [ :int, :pointer ], :void ],
    [ :ShadeModel, [ :uint ], :void ],
    [ :StencilFunc, [ :uint, :int, :uint ], :void ],
    [ :StencilMask, [ :uint ], :void ],
    [ :StencilOp, [ :uint, :uint, :uint ], :void ],
    [ :TexCoord1d, [ :double ], :void ],
    [ :TexCoord1dv, [ :pointer ], :void ],
    [ :TexCoord1f, [ :float ], :void ],
    [ :TexCoord1fv, [ :pointer ], :void ],
    [ :TexCoord1i, [ :int ], :void ],
    [ :TexCoord1iv, [ :pointer ], :void ],
    [ :TexCoord1s, [ :short ], :void ],
    [ :TexCoord1sv, [ :pointer ], :void ],
    [ :TexCoord2d, [ :double, :double ], :void ],
    [ :TexCoord2dv, [ :pointer ], :void ],
    [ :TexCoord2f, [ :float, :float ], :void ],
    [ :TexCoord2fv, [ :pointer ], :void ],
    [ :TexCoord2i, [ :int, :int ], :void ],
    [ :TexCoord2iv, [ :pointer ], :void ],
    [ :TexCoord2s, [ :short, :short ], :void ],
    [ :TexCoord2sv, [ :pointer ], :void ],
    [ :TexCoord3d, [ :double, :double, :double ], :void ],
    [ :TexCoord3dv, [ :pointer ], :void ],
    [ :TexCoord3f, [ :float, :float, :float ], :void ],
    [ :TexCoord3fv, [ :pointer ], :void ],
    [ :TexCoord3i, [ :int, :int, :int ], :void ],
    [ :TexCoord3iv, [ :pointer ], :void ],
    [ :TexCoord3s, [ :short, :short, :short ], :void ],
    [ :TexCoord3sv, [ :pointer ], :void ],
    [ :TexCoord4d, [ :double, :double, :double, :double ], :void ],
    [ :TexCoord4dv, [ :pointer ], :void ],
    [ :TexCoord4f, [ :float, :float, :float, :float ], :void ],
    [ :TexCoord4fv, [ :pointer ], :void ],
    [ :TexCoord4i, [ :int, :int, :int, :int ], :void ],
    [ :TexCoord4iv, [ :pointer ], :void ],
    [ :TexCoord4s, [ :short, :short, :short, :short ], :void ],
    [ :TexCoord4sv, [ :pointer ], :void ],
    [ :TexCoordPointer, [ :int, :uint, :int, :pointer ], :void ],
    [ :TexEnvf, [ :uint, :uint, :float ], :void ],
    [ :TexEnvfv, [ :uint, :uint, :pointer ], :void ],
    [ :TexEnvi, [ :uint, :uint, :int ], :void ],
    [ :TexEnviv, [ :uint, :uint, :pointer ], :void ],
    [ :TexGend, [ :uint, :uint, :double ], :void ],
    [ :TexGendv, [ :uint, :uint, :pointer ], :void ],
    [ :TexGenf, [ :uint, :uint, :float ], :void ],
    [ :TexGenfv, [ :uint, :uint, :pointer ], :void ],
    [ :TexGeni, [ :uint, :uint, :int ], :void ],
    [ :TexGeniv, [ :uint, :uint, :pointer ], :void ],
    [ :TexImage1D, [ :uint, :int, :int, :int, :int, :uint, :uint, :pointer ], :void ],
    [ :TexImage2D, [ :uint, :int, :int, :int, :int, :int, :uint, :uint, :pointer ], :void ],
    [ :TexParameterf, [ :uint, :uint, :float ], :void ],
    [ :TexParameterfv, [ :uint, :uint, :pointer ], :void ],
    [ :TexParameteri, [ :uint, :uint, :int ], :void ],
    [ :TexParameteriv, [ :uint, :uint, :pointer ], :void ],
    [ :TexSubImage1D, [ :uint, :int, :int, :int, :uint, :uint, :pointer ], :void ],
    [ :TexSubImage2D, [ :uint, :int, :int, :int, :int, :int, :uint, :uint, :pointer ], :void ],
    [ :Translated, [ :double, :double, :double ], :void ],
    [ :Translatef, [ :float, :float, :float ], :void ],
    [ :Vertex2d, [ :double, :double ], :void ],
    [ :Vertex2dv, [ :pointer ], :void ],
    [ :Vertex2f, [ :float, :float ], :void ],
    [ :Vertex2fv, [ :pointer ], :void ],
    [ :Vertex2i, [ :int, :int ], :void ],
    [ :Vertex2iv, [ :pointer ], :void ],
    [ :Vertex2s, [ :short, :short ], :void ],
    [ :Vertex2sv, [ :pointer ], :void ],
    [ :Vertex3d, [ :double, :double, :double ], :void ],
    [ :Vertex3dv, [ :pointer ], :void ],
    [ :Vertex3f, [ :float, :float, :float ], :void ],
    [ :Vertex3fv, [ :pointer ], :void ],
    [ :Vertex3i, [ :int, :int, :int ], :void ],
    [ :Vertex3iv, [ :pointer ], :void ],
    [ :Vertex3s, [ :short, :short, :short ], :void ],
    [ :Vertex3sv, [ :pointer ], :void ],
    [ :Vertex4d, [ :double, :double, :double, :double ], :void ],
    [ :Vertex4dv, [ :pointer ], :void ],
    [ :Vertex4f, [ :float, :float, :float, :float ], :void ],
    [ :Vertex4fv, [ :pointer ], :void ],
    [ :Vertex4i, [ :int, :int, :int, :int ], :void ],
    [ :Vertex4iv, [ :pointer ], :void ],
    [ :Vertex4s, [ :short, :short, :short, :short ], :void ],
    [ :Vertex4sv, [ :pointer ], :void ],
    [ :VertexPointer, [ :int, :uint, :int, :pointer ], :void ],
    [ :Viewport, [ :int, :int, :int, :int ], :void ]
  ]

  @functions.each { |name, args, ret| attach_function name, "gl#{name}", args, ret }
end